name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          node-version-files: "frontend/package.json"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm run test:console
